name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
jobs:
  # Check formatting and run clippy lints
  linting:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  # Build the workspace with the feature permutations not built by default
  features:
    strategy:
      fail-fast: false
      matrix:
        feature-args:
          - "--no-default-features"
          - "--no-default-features --features serial"
          - "--no-default-features --features tls"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Caching
        uses: Swatinem/rust-cache@v1
      - name: Build the workspace with the features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args:  --release ${{ matrix.feature-args }}
  # Run the unit tests on Windows and Linux
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        rust:
          - stable
          - beta
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Copy Windows config
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: Copy-Item -Path .cargo/config-windows.toml -Destination .cargo/config.toml
      - name: Caching
        uses: Swatinem/rust-cache@v2
      - name: Run Rust unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
  # Build API documentation packages
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install doxygen 1.9.3
        run: wget -q https://www.doxygen.nl/files/doxygen-1.9.3.linux.bin.tar.gz -O- | sudo tar --strip-components=1 -C /usr -xz doxygen-1.9.3
      - name: Caching
        uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Build Rustdoc
        run: cargo doc -p rodbus --no-deps
      - name: C bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin rodbus-bindings -- --c --doxygen
      - name: .NET bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin rodbus-bindings -- --dotnet --doxygen
      - name: Java bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin rodbus-bindings -- --java
      - name: Extract documentation
        run: |
          mkdir -p ~/doc
          cp -a target/doc ~/doc/rust
          cp -a ffi/bindings/c/generated/doc/c ~/doc/c
          cp -a ffi/bindings/c/generated/doc/cpp ~/doc/cpp
          cp -a ffi/bindings/dotnet/rodbus/doc ~/doc/dotnet
          cp -a ffi/bindings/java/rodbus/target/apidocs ~/doc/java
          rm ffi/bindings/c/generated/logo.png ffi/bindings/c/generated/doxygen-awesome.css
      - name: Upload documentation
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: ~/doc
  # Build bindings on Windows x64 [64-bit MSVC (Windows 7+) (x86_64-pc-windows-msvc)] and x86 [32-bit MSVC (Windows 7+) (i686-pc-windows-msvc)]
  bindings-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc # 64-bit MSVC (Windows 7+)
            extra-param: # nothing
          - target: i686-pc-windows-msvc # 32-bit MSVC (Windows 7+)
            extra-params: --no-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Copy Windows config
        shell: pwsh
        run: Copy-Item -Path .cargo/config-windows.toml -Destination .cargo/config.toml
      - name: Caching
        uses: Swatinem/rust-cache@v2
      - name: Create log dir
        run: mkdir logs\${{ matrix.target }}
      - name: Build FFI
        run: cargo build -p rodbus-ffi --release --target ${{ matrix.target }} --message-format json | Out-File -encoding "UTF8" .\logs\${{ matrix.target }}\build.ffi.log
      - name: Build JNI
        run: cargo build -p rodbus-ffi-java --release --target ${{ matrix.target }} --message-format json | Out-File -encoding "UTF8" .\logs\${{ matrix.target }}\build.jni.log
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: logs
      - name: C bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --target ${{ matrix.target }} --bin rodbus-bindings -- --c ${{ matrix.extra-params }}
      - name: .NET bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --target ${{ matrix.target }} --bin rodbus-bindings -- --dotnet ${{ matrix.extra-params }}
      - name: Java bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --target ${{ matrix.target }} --bin rodbus-bindings -- --java ${{ matrix.extra-params }}
      - name: Upload compiled FFI modules
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: ffi/bindings/c/generated/${{ matrix.target }}/lib
      - name: Upload C bindings
        uses: actions/upload-artifact@v3
        with:
          name: c-bindings
          path: ffi/bindings/c/generated
      - name: Upload compiled Java bindings
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: ffi/bindings/java/rodbus/src/main/resources
  # Build bindings on MacOS [64-bit macOS (10.7+, Lion+) (x86_64-apple-darwin)]
  bindings-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Caching
        uses: Swatinem/rust-cache@v2
      - name: Create Log Dir
        run: mkdir -p logs/x86_64-apple-darwin
      - name: Build FFI
        run: cargo build -p rodbus-ffi --release --message-format json > logs/x86_64-apple-darwin/build.ffi.log
      - name: Build JNI
        run: cargo build -p rodbus-ffi-java --release --message-format json > logs/x86_64-apple-darwin/build.jni.log
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: logs
      - name: C bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin rodbus-bindings -- --c
      - name: .NET bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin rodbus-bindings -- --dotnet
      - name: Java bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --bin rodbus-bindings -- --java
      - name: Upload compiled FFI modules
        uses: actions/upload-artifact@v2
        with:
          name: ffi-modules
          path: ffi/bindings/c/generated/x86_64-apple-darwin/lib
      - name: Upload C bindings
        uses: actions/upload-artifact@v2
        with:
          name: c-bindings
          path: ffi/bindings/c/generated
      - name: Upload compiled Java bindings
        uses: actions/upload-artifact@v2
        with:
          name: ffi-modules
          path: ffi/bindings/java/rodbus/src/main/resources
  # Cross-compilation for ARM devices and produce C bindings
  cross:
    strategy:
      fail-fast: false
      matrix:
        target:
          - arm-unknown-linux-gnueabi # ARMv6 Linux (kernel 3.2, glibc 2.17)
          - arm-unknown-linux-gnueabihf # ARMv6 Linux, hardfloat (kernel 3.2, glibc 2.17)
          - armv7-unknown-linux-gnueabihf # ARMv7 Linux, hardfloat (kernel 3.2, glibc 2.17)
          - aarch64-unknown-linux-gnu # ARM64 Linux (kernel 4.2, glibc 2.17+)
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu # 64-bit Linux (kernel 2.6.32+, glibc 2.11+)
          - x86_64-unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install Rust Cross
        run: cargo install cross
      - name: Create Log Dir
        run: mkdir -p logs/${{ matrix.target }}
      - name: Build FFI
        run: cross build -p rodbus-ffi --release --target ${{ matrix.target }} --message-format json > logs/${{ matrix.target }}/build.ffi.log
      - name: Build JNI
        run: cross build -p rodbus-ffi-java --release --target ${{ matrix.target }} --message-format json > logs/${{ matrix.target }}/build.jni.log
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: logs
      - name: C bindings
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: run
          args: --release --target ${{ matrix.target }} --bin rodbus-bindings -- --c --no-tests
      - name: Java bindings
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: run
          args: --release --target ${{ matrix.target }} --bin rodbus-bindings -- --java --no-tests
      - name: Upload compiled Java bindings
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: ffi/bindings/java/rodbus/src/main/resources
      - name: Upload compiled FFI modules
        uses: actions/upload-artifact@v3
        with:
          name: ffi-modules
          path: ffi/bindings/c/generated/${{ matrix.target }}/lib
      - name: Upload C bindings
        uses: actions/upload-artifact@v3
        with:
          name: c-bindings
          path: ffi/bindings/c/generated
  guide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: guide
        run: yarn install
      - name: Build guide
        working-directory: guide
        run: |
         yarn build
         mkdir -p ~/doc/guide
         mv build/* ~/doc/guide
      - name: Upload guide
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: ~/doc
  # Package all the generated bindings
  packaging:
    needs: [documentation, bindings-windows, bindings-macos, cross]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Caching
        uses: Swatinem/rust-cache@v2
      - name: Checkout BOM tools repo
        uses: actions/checkout@v3
        with:
          repository: stepfunc/bom-tools
          ref: 0.1.0
          path: bom-tools
      - name: Install BOM tools
        working-directory: bom-tools
        run: cargo install --path bom-tools
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download compiled FFI
        uses: actions/download-artifact@v2
        with:
          name: ffi-modules
          path: ffi-modules
      - name: Create FFI third-party-licenses.txt
        run: bom-tools gen-licenses-dir ./ffi-modules build.ffi.log ./dep_config.json > third-party-licenses.txt
      - name: Package .NET bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin rodbus-bindings -- --dotnet --package ./ffi-modules -f third-party-licenses.txt
      - name: Create JNI third-party-licenses.txt
        run: bom-tools gen-licenses-dir ./ffi-modules build.jni.log ./dep_config.json > third-party-licenses.txt
      - name: Package Java bindings
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin rodbus-bindings -- --java --package ./ffi-modules -f third-party-licenses.txt
      - name: Upload .NET bindings
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-bindings
          path: ffi/bindings/dotnet/nupkg/*
      - name: Upload Java bindings
        uses: actions/upload-artifact@v2
        with:
          name: java-bindings
          path: ffi/bindings/java/rodbus/target/*.jar
      - name: Upload Java pom.xml
        uses: actions/upload-artifact@v2
        with:
          name: java-bindings
          path: ffi/bindings/java/rodbus/pom.xml
  release:
    needs: [packaging, guide]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Checkout stepfunc/docs
        uses: actions/checkout@v3
        with:
          repository: stepfunc/docs
          ssh-key: ${{ secrets.SFIO_DOCS_SSH_KEY }}
          path: docs
      - name: Upload docs
        working-directory: docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf ./rodbus/${GITHUB_REF##*/}
          mkdir -p ./rodbus/${GITHUB_REF##*/}
          cp -a ../artifacts/doc/* ./rodbus/${GITHUB_REF##*/}
          git add -A
          git commit -m "[rodbus] Release ${GITHUB_REF##*/}"
          git push
      - name: Import PGP key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.SFIO_PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.SFIO_PGP_PRIVATE_KEY_PASSPHRASE }}
      - name: Login to OSSRH
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.SFIO_OSSRH_USERNAME }}", "password": "${{ secrets.SFIO_OSSRH_PASSWORD }}" }]'
      - name: Deploy Java
        shell: bash
        working-directory: artifacts/java-bindings
        run: >
          shopt -s extglob &&
          mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2 -DrepositoryId=ossrh -DpomFile=pom.xml -Dfile=$(find rodbus-+([0-9]).+([0-9]).+([0-9]).jar) &&
          mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2 -DrepositoryId=ossrh -DpomFile=pom.xml -Dfile=$(find rodbus-+([0-9]).+([0-9]).+([0-9])-sources.jar) -Dclassifier=sources &&
          mvn gpg:sign-and-deploy-file -Durl=https://oss.sonatype.org/service/local/staging/deploy/maven2 -DrepositoryId=ossrh -DpomFile=pom.xml -Dfile=$(find rodbus-+([0-9]).+([0-9]).+([0-9])-javadoc.jar) -Dclassifier=javadoc
      - name: Publish NuGet package
        shell: bash
        run: dotnet nuget push $(find artifacts/dotnet-bindings/rodbus*.nupkg) -s https://api.nuget.org/v3/index.json -k ${{ secrets.SFIO_NUGET_KEY }}
      - name: Package C bindings
        shell: bash
        run: >
          mkdir release &&
          for i in artifacts/c-bindings/*; do (cd $i && zip -r ../../../release/rodbus-${GITHUB_REF##*/}-$(basename $i).zip .); done
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            release/*.zip
            artifacts/dotnet-bindings/rodbus*
            artifacts/java-bindings/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
